<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Auth\Middleware\Authenticate as Middleware;

class Authenticate extends Middleware
{

    public function handle($request, Closure $next, ...$guards)
    {
        $token = trim($request->bearerToken());
        if (strlen($token) == 0)
            throw new AuthenticationException('Unauthenticated.');
        $token       = explode(' ', $token);
        $clientToken = @$token[0];
        $userToken   = @$token[1];

        return parent::handle($request, $next, $guards); // TODO: Change the autogenerated stub
    }

    /**
     * Get the path the user should be redirected to when they are not authenticated.
     *
     * @param \Illuminate\Http\Request $request
     * @return string|null
     */
    protected function redirectTo($request)
    {
        if (!$request->expectsJson()) {
            return route('login');
        }
    }
}
